component-vertiv:
  - changed-files:
      - any-glob-to-any-file: custom_components/vertiv/**

translations:
  - changed-files:
      - any-glob-to-any-file: custom_components/vertiv/translations/**

docs:
  - changed-files:
      - any-glob-to-any-file: custom_components/vertiv/**/*.md
